# Generated by Django 2.0.6 on 2018-06-07 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamId', models.CharField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
