# Generated by Django 2.0.6 on 2018-06-18 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0002_questions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='questions',
            new_name='question',
        ),
    ]
