# Generated by Django 2.0.6 on 2018-06-19 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0003_auto_20180618_1317'),
    ]

    operations = [
        migrations.DeleteModel(
            name='question',
        ),
    ]
