# Generated by Django 2.0.6 on 2018-06-19 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0005_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='statement',
            field=models.CharField(max_length=5000, unique=True),
        ),
    ]
