# Generated by Django 2.0.6 on 2018-06-25 06:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('contest', '0006_auto_20180619_0709'),
    ]

    operations = [
        migrations.CreateModel(
            name='timeRemaining',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('time', models.IntegerField(max_length=5000)),
            ],
        ),
    ]
