# Generated by Django 2.0.6 on 2018-06-25 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0007_timeremaining'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeremaining',
            name='completion',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='timeremaining',
            name='time',
            field=models.IntegerField(),
        ),
    ]
