# Generated by Django 2.0.6 on 2018-07-01 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('contest', '0008_auto_20180625_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='submission',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('question1', models.CharField(max_length=50)),
                ('question2', models.CharField(max_length=50)),
                ('question3', models.CharField(max_length=50)),
                ('question4', models.CharField(max_length=50)),
                ('question5', models.CharField(max_length=50)),
                ('penalty', models.IntegerField()),
                ('marks', models.IntegerField()),
                ('time', models.IntegerField()),
            ],
        ),
    ]
