# Generated by Django 2.0.6 on 2018-07-01 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0009_submission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='marks',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='time',
        ),
    ]
