# Generated by Django 2.0.6 on 2018-07-01 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0010_auto_20180701_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='submission',
            name='time',
            field=models.IntegerField(default=0),
        ),
    ]
