# Generated by Django 2.0.6 on 2018-07-01 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0011_auto_20180701_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='question1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='question2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='question3',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='question4',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='question5',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
