# Generated by Django 2.0.6 on 2018-07-01 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0012_auto_20180701_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='penalty',
            field=models.IntegerField(null=True),
        ),
    ]
