# Generated by Django 2.0.6 on 2018-07-01 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0013_auto_20180701_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='time',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
