# Generated by Django 2.0.6 on 2018-07-02 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0014_auto_20180701_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='penalty',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
